/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_AddCpp */

#ifndef _Included_test_AddCpp
#define _Included_test_AddCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_AddCpp
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_test_AddCpp_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
