/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_ReturnArray */

#ifndef _Included_test_ReturnArray
#define _Included_test_ReturnArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_ReturnArray
 * Method:    returnIntArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_test_ReturnArray_returnIntArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
