/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_MyClassWrapper */

#ifndef _Included_test_MyClassWrapper
#define _Included_test_MyClassWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_MyClassWrapper
 * Method:    callNative
 * Signature: (Ltest/MyClassWrapper;)V
 */
JNIEXPORT void JNICALL Java_test_MyClassWrapper_callNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
